### ISSUE TITLE
Command/Event Requests

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Denizen2Sponge#19]
Drop Command:
- Drop any item at a certain location

On Player Right-Clicks With:
- An event that is triggered when a player is holding something in their hand, good for a token/loot system

On Player Executes Command
- An event that is triggered when a player runs a command, allows to intercept commands before plugins, create aliases etc.

Skull/Skull_Skin tags:
- Current using this for a lucky block script in D1, it's formatted like:
<context.location.skull_skin.contains[skin-uuid]>
- Would be great if I can port it over to D2

Random:
- Generate random numbers useful for lots of things
D1: <util.random.int[1].to[8]> 

- [x] drop
- [x] right click
- [x] skull tags
- [x] random
- [x] on player executes command

**Comment by mcmonkey4eva** [comment]
Random has been added via https://github.com/DenizenScript/Denizen2Core/commit/bf0d66ca01b79a4673ba96b4d25d282ba3aee26a

**Comment by mcmonkey4eva** [comment]
Also, I turned your issue into a checklist :D

**Comment by mcmonkey4eva** [comment]
Towards the purposes of making this work, I've also added a 'with_item:' switch for events to use.

**Comment by Xenmai** [comment]
I added that drop command and right click event. Skull tags seem to be giving me problems, so they'll have to wait until we manage to fix them.

**Comment by GershonR** [comment]
Thanks for the updates did the documentation get updated for scripting?

Also, a on player executes command event would be really nice, I just realized I wanted to create some aliases for some commands for players to run, I added it to the checklist.

**Comment by mcmonkey4eva** [comment]
You should default to using a command script, not using a command event. A command event is to partially override an existing command.

**Comment by GershonR** [comment]
Yeah, i'm trying to override a current command.

**Comment by mcmonkey4eva** [comment]
command event done!

**Comment by Xenmai** [comment]
Skull stuff is fixed so I added the tags!

**Comment by mcmonkey4eva** [comment]
@Xenmai I think we need more skull tags:
Skin, UUID, etc. not just name

**Comment by mcmonkey4eva** [comment]
All requests complete :D
