### ISSUE TITLE
Duration to flag command

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Denizen2Sponge#25]
Add a duration to a flag to allow to expire after a certain period of time.

Example D1: flag <player> cool_flag:true duration:1m

**Comment by mcmonkey4eva** [comment]
I think for this to work,
we'd have a separate map alongside the initial map.
This second map represents any duration.
Probably tags would have the option to ignore duration caps, or include them (defaulting to include them)
Command would have durations as an optional argument.

**Comment by mcmonkey4eva** [comment]
Done!
