### ISSUE TITLE
Play custom sounds from resource pack

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Denizen2Sponge#26]
Ability to play a custom sound from a resource pack.

Usage in D1: "playsound <player.location> sound:cool.sound custom"

**Comment by mcmonkey4eva** [comment]
I think the way sponge works, is it expects any sound types to be registered.
Therefore I think the solution to this is to have a command to register a new sound type!

**Comment by Xenmai** [comment]
In the end we managed to implement custom sound types directly to playsound without the need of a new command. Example for a loud (volume 2) custom cannon sound: - playsound <player.location> pirate_cannon 2 --custom true
