### ISSUE TITLE
Wait command doesn't work.

### ISSUE THREAD

**Issue by FallenVFX** [DenizenScript/Denizen2Sponge#29]
When using the wait command it runs the code before and then when it reaches the wait command it says "waiting for 1 seconds" and then nothing happens, the script just ends without running anything past the wait command. here is a sample script where this happens.

Testtask:
    type: task
    script:
    - echo "before wait"
    - wait 1s
    - echo "after wait"

**Comment by mcmonkey4eva** [comment]
IIRC this issue was fixed forever ago? If not leave a comment and will look into more closely.
