### ISSUE TITLE
NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ziceptor** [DenizenScript/Denizen2Sponge#47]
https://gist.github.com/ziceptor/0ca533c07eb189676341e43355954f22

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2747.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar

**Comment by Xenmai** [comment]
Could you explain how did you get this error? I'm trying to reproduce it but no luck. I'm using an "on player left clicks block:" event and it works just fine, as intended. I wonder what are the circumstances that make it error in your case. So yeah, provide more information please.

**Comment by ziceptor** [comment]
forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2797.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar

\config\denizen\scripts\halloween.yml
```
Halloween_Treasure_Hunt:
  type: world
  debug: full
  events:
    on player left clicks block type:lit_pumpkin world:custom:
    - setblock <context.location> air
    - foreach start <server.online_players>:
      - give <def[foreach_value]> diamond
    - announce "<player.name> nagrazhden!"
```
Perhaps due to changes sponge http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.12.2-2555-7.0.0-BETA-2799/spongeforge-1.12.2-2555-7.0.0-BETA-2799-changelog.txt

**Comment by ziceptor** [comment]
```
Build 1347:
	gabizou:
		Bump common for pumpkin optimization.
		
		Signed-off-by: Gabriel Harris-Rouquette <gabizou@me.com>
```

**Comment by ziceptor** [comment]
It's still not fixed :(

**Comment by ziceptor** [comment]
forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2916.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar (Xenmai)

re-created the world

Not any errors.

**Comment by ziceptor** [comment]
Looks like the problem remains.
https://gist.github.com/ziceptor/ea3372c0f7fb2948cf04d42afcdf726b

Creative. Broke a lot of trees. Empty hand.


forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar

**Comment by ziceptor** [comment]
No error if the folder `..\config\denizen\scripts` is empty.

I have three of the world: hub (primary), wn and wf.

halloween.yml

```
Halloween_Treasure_Hunt:
  type: world
  debug: full
  events:
    on player left clicks block type:lit_pumpkin world:wn:
    - setblock <context.location> air
    - foreach start <server.online_players>:
      - give <def[foreach_value]> diamond
    - announce "<player.name> nagrazhden!"
```
The error occurs if you hold down the left mouse button (continuously break).
The error occurs when you press a series of left mouse button (click, click, click).
The error occurs in all worlds.

**Comment by ziceptor** [comment]
An error occurs when the hand is empty.
The error occurs when the hand is not empty.

**Comment by mcmonkey4eva** [comment]
Sent in a patch for latest version, should prevent errors.

**Comment by ziceptor** [comment]
I checked. There are no errors. If you are, I will inform you. Thank You!
